### ISSUE TITLE
'https://api.paywhirl.com/account' has been blocked by CORS.

### ISSUE THREAD

**Issue by shubhamteotia09** [paywhirl/node-pwclient#19]
I have installed paywhirl package using NPM and ran the below code in my vue app:
**Code**:
const PayWhirl = require('paywhirl');
const apiKey = 'pwpk_xxxxxxxxxxxxxxx';
const apiSecret = 'pwpsk_xxxxxxxxxxx';
const paywhirl = new PayWhirl(apiKey, apiSecret);
paywhirl.getAccount().then(console.log);

**Error**:
Access to fetch at 'https://api.paywhirl.com/account' from origin 'http://localhost:8080' has been blocked by CORS policy: Request header field api-key is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by danetzer** [comment]
> I have installed paywhirl package using NPM and ran the below code in my vue app:
> **Code**:
> const PayWhirl = require('paywhirl');
> const apiKey = 'pwpk_xxxxxxxxxxxxxxx';
> const apiSecret = 'pwpsk_xxxxxxxxxxx';
> const paywhirl = new PayWhirl(apiKey, apiSecret);
> paywhirl.getAccount().then(console.log);
> 
> **Error**:
> Access to fetch at 'https://api.paywhirl.com/account' from origin 'http://localhost:8080' has been blocked by CORS policy: Request header field api-key is not allowed by Access-Control-Allow-Headers in preflight response.

@shubhamteotia09 There are a few issues here: 1) you'll have CORS issues if using this code on the client side 2) your api key will be exposed as well, which you don't want for obvious reasons. 

You should be running this code from the back-end where you can solve these problems.

**Comment by shubhamteotia09** [comment]
@danetzer Thank you.
